stages:
  - build
 # - deploy

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  artifacts:
    paths:
      - public
  
#deploy:
#  stage: deploy
#  image: alpine:latest
#  before_script:
#    - apk add --update --no-cache rsync openssh-client
#    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
#    - echo ${SSH_PRIVATE_KEY} | base64 -d > ~/.ssh/id_rsa
#    - chmod 600 ~/.ssh/id_rsa
#    - ssh-keyscan -t rsa ${DO_HOST} >> ~/.ssh/known_hosts
#  script:
#    - rsync -az --delete public/ ${DO_USER}@${DO_HOST}:${DO_PATH}
#  only:
#    - master