stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  
deploy:
  stage: deploy
  image: instrumentisto/rsync-ssh:latest
  before_script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "${SSH_PRIVATE_KEY}")'
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -t rsa ${REMOTE_HOST_NAME} >> ~/.ssh/known_hosts
  script:
    - rsync -azhv --delete public/ "${SSH_USER_HOST_LOCATION}"
  only:
    - master