baseURL = "https://docs.libreweb.org"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "LibreWeb Documentation"
theme = "libredocs"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://gitlab.melroy.org/libreweb/docs-website/-/tree/master/content/"
  description = "LibreWeb Documentation"
  author = "Melroy van den Berg"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  ordersectionsby = "weight"
  themeVariant = "blue"
  # For create diagrams enable Mermaid
  disableMermaid = true
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "-"
  landingPageName = "<i class='fas fa-home'></i>&nbsp;Home"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i>&nbsp;GitLab Project"
identifier = "repo"
url = "https://gitlab.melroy.org/libreweb"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON"]

#[Languages]
#[Languages.en]
#title = "LibreWeb Documentation"
#weight = 1
#languageName = "English"
#landingPageURL = "/en"
#landingPageName = "<i class='fas fa-home'></i> Home"
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
#identifier = "ds"
#url = "https://github.com/matcornic/hugo-theme-learn"
#weight = 10
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-camera'></i> Showcases"
#url = "showcase"
#weight = 11
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30
